name: Semgrep SAST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep/custom-rules.yml
